// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetMentor.DemoEF.CodeFirst.Data.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetMentor.DemoEF.CodeFirst.Data.Migrations
{
    [DbContext(typeof(NorthwindContext))]
    [Migration("20241230053715_CargaInicial")]
    partial class CargaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeneroPelicula", b =>
                {
                    b.Property<int>("GenerosId")
                        .HasColumnType("integer");

                    b.Property<int>("PeliculasId")
                        .HasColumnType("integer");

                    b.HasKey("GenerosId", "PeliculasId");

                    b.HasIndex("PeliculasId");

                    b.ToTable("GeneroPelicula");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastUpdateTimeUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Email = "example-5@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-5"
                        },
                        new
                        {
                            Id = 6,
                            Email = "example-6@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-6"
                        },
                        new
                        {
                            Id = 7,
                            Email = "example-7@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-7"
                        },
                        new
                        {
                            Id = 8,
                            Email = "example-8@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-8"
                        },
                        new
                        {
                            Id = 9,
                            Email = "example-9@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-9"
                        },
                        new
                        {
                            Id = 10,
                            Email = "example-10@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-10"
                        },
                        new
                        {
                            Id = 11,
                            Email = "example-11@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-11"
                        },
                        new
                        {
                            Id = 12,
                            Email = "example-12@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-12"
                        },
                        new
                        {
                            Id = 13,
                            Email = "example-13@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-13"
                        },
                        new
                        {
                            Id = 14,
                            Email = "example-14@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-14"
                        },
                        new
                        {
                            Id = 15,
                            Email = "example-15@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-15"
                        },
                        new
                        {
                            Id = 16,
                            Email = "example-16@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-16"
                        },
                        new
                        {
                            Id = 17,
                            Email = "example-17@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-17"
                        },
                        new
                        {
                            Id = 18,
                            Email = "example-18@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-18"
                        },
                        new
                        {
                            Id = 19,
                            Email = "example-19@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-19"
                        },
                        new
                        {
                            Id = 20,
                            Email = "example-20@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-20"
                        },
                        new
                        {
                            Id = 21,
                            Email = "example-21@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-21"
                        },
                        new
                        {
                            Id = 22,
                            Email = "example-22@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-22"
                        },
                        new
                        {
                            Id = 23,
                            Email = "example-23@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-23"
                        },
                        new
                        {
                            Id = 24,
                            Email = "example-24@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-24"
                        },
                        new
                        {
                            Id = 25,
                            Email = "example-25@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-25"
                        },
                        new
                        {
                            Id = 26,
                            Email = "example-26@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-26"
                        },
                        new
                        {
                            Id = 27,
                            Email = "example-27@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-27"
                        },
                        new
                        {
                            Id = 28,
                            Email = "example-28@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-28"
                        },
                        new
                        {
                            Id = 29,
                            Email = "example-29@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-29"
                        },
                        new
                        {
                            Id = 30,
                            Email = "example-30@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-30"
                        },
                        new
                        {
                            Id = 31,
                            Email = "example-31@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-31"
                        },
                        new
                        {
                            Id = 32,
                            Email = "example-32@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-32"
                        },
                        new
                        {
                            Id = 33,
                            Email = "example-33@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-33"
                        },
                        new
                        {
                            Id = 34,
                            Email = "example-34@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-34"
                        },
                        new
                        {
                            Id = 35,
                            Email = "example-35@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-35"
                        },
                        new
                        {
                            Id = 36,
                            Email = "example-36@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-36"
                        },
                        new
                        {
                            Id = 37,
                            Email = "example-37@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-37"
                        },
                        new
                        {
                            Id = 38,
                            Email = "example-38@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-38"
                        },
                        new
                        {
                            Id = 39,
                            Email = "example-39@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-39"
                        },
                        new
                        {
                            Id = 40,
                            Email = "example-40@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-40"
                        },
                        new
                        {
                            Id = 41,
                            Email = "example-41@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-41"
                        },
                        new
                        {
                            Id = 42,
                            Email = "example-42@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-42"
                        },
                        new
                        {
                            Id = 43,
                            Email = "example-43@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-43"
                        },
                        new
                        {
                            Id = 44,
                            Email = "example-44@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-44"
                        },
                        new
                        {
                            Id = 45,
                            Email = "example-45@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-45"
                        },
                        new
                        {
                            Id = 46,
                            Email = "example-46@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-46"
                        },
                        new
                        {
                            Id = 47,
                            Email = "example-47@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-47"
                        },
                        new
                        {
                            Id = 48,
                            Email = "example-48@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-48"
                        },
                        new
                        {
                            Id = 49,
                            Email = "example-49@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-49"
                        },
                        new
                        {
                            Id = 50,
                            Email = "example-50@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-50"
                        },
                        new
                        {
                            Id = 51,
                            Email = "example-51@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-51"
                        },
                        new
                        {
                            Id = 52,
                            Email = "example-52@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-52"
                        },
                        new
                        {
                            Id = 53,
                            Email = "example-53@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-53"
                        },
                        new
                        {
                            Id = 54,
                            Email = "example-54@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-54"
                        },
                        new
                        {
                            Id = 55,
                            Email = "example-55@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-55"
                        },
                        new
                        {
                            Id = 56,
                            Email = "example-56@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-56"
                        },
                        new
                        {
                            Id = 57,
                            Email = "example-57@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-57"
                        },
                        new
                        {
                            Id = 58,
                            Email = "example-58@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-58"
                        },
                        new
                        {
                            Id = 59,
                            Email = "example-59@gmail.com",
                            LastUpdateTimeUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            State = (byte)1,
                            UserName = "user-name-59"
                        });
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.Models.WorkingExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Environment")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkingExperiences");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografia")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Actor");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Cine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cine");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genero");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnCartelera")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PosterURL")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.PeliculaActor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("integer");

                    b.Property<string>("Personaje")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("PeliculaId");

                    b.ToTable("PeliculaActor");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.SalaDeCine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CineId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int?>("TipoSalaDeCineId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CineId");

                    b.HasIndex("TipoSalaDeCineId");

                    b.ToTable("SalaDeCine");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.TipoSalaDeCine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("TipoSalaDeCine");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.UserResponseBd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UsersResponseBd");
                });

            modelBuilder.Entity("PeliculaSalaDeCine", b =>
                {
                    b.Property<int>("PeliculasId")
                        .HasColumnType("integer");

                    b.Property<int>("SalasDeCineId")
                        .HasColumnType("integer");

                    b.HasKey("PeliculasId", "SalasDeCineId");

                    b.HasIndex("SalasDeCineId");

                    b.ToTable("PeliculaSalaDeCine");
                });

            modelBuilder.Entity("GeneroPelicula", b =>
                {
                    b.HasOne("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Genero", null)
                        .WithMany()
                        .HasForeignKey("GenerosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("PeliculasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.Models.WorkingExperience", b =>
                {
                    b.HasOne("NetMentor.DemoEF.CodeFirst.Entities.Models.User", "User")
                        .WithMany("WorkingExperiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.PeliculaActor", b =>
                {
                    b.HasOne("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Actor", "Actor")
                        .WithMany("PeliculasActores")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Pelicula", "Pelicula")
                        .WithMany("PeliculaActores")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.SalaDeCine", b =>
                {
                    b.HasOne("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Cine", "Cine")
                        .WithMany("SalasDeCine")
                        .HasForeignKey("CineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.TipoSalaDeCine", "TipoSalaDeCine")
                        .WithMany()
                        .HasForeignKey("TipoSalaDeCineId");

                    b.Navigation("Cine");

                    b.Navigation("TipoSalaDeCine");
                });

            modelBuilder.Entity("PeliculaSalaDeCine", b =>
                {
                    b.HasOne("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Pelicula", null)
                        .WithMany()
                        .HasForeignKey("PeliculasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.SalaDeCine", null)
                        .WithMany()
                        .HasForeignKey("SalasDeCineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.Models.User", b =>
                {
                    b.Navigation("WorkingExperiences");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Actor", b =>
                {
                    b.Navigation("PeliculasActores");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Cine", b =>
                {
                    b.Navigation("SalasDeCine");
                });

            modelBuilder.Entity("NetMentor.DemoEF.CodeFirst.Entities.ResponseBd.Pelicula", b =>
                {
                    b.Navigation("PeliculaActores");
                });
#pragma warning restore 612, 618
        }
    }
}
