version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_desa
    restart: always
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      - MYSQL_ROOT_PASSWORD=Abc123+-*
      - MYSQL_DATABASE=dbnorthwind
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=123456      
    ports:
      - "3306:3306"
    volumes:
      - "db_data:/var/lib/mysql"

volumes:
  db_data:
